version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin port

  authentication:
    build:
      context: ./AlertHawk.Authentication
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8085:80"  # Expose internal port 80 to host

  monitoring:
    build:
      context: ./AlertHawk.Monitoring
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8086:80"  # Expose internal port 80 to host

  notification:
    build:
      context: ./AlertHawk.Notification
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8087:80"  # Expose internal port 80 to host

volumes:
  rabbitmq_data:
